server:
  port: ${PORT:8080}
  servlet:
    application-display-name: electroplus-service

spring:
  application:
    name: electroplus-service

  datasource:
    url: jdbc:postgresql://ec2-44-206-89-185.compute-1.amazonaws.com:5432/d4qc2n6fsa0t8q
    username: fgwkyhlyocplss
    password: 17c5a4a64bfa79f94645965006c3debf6e4c78bfa6bae98d716221a850eda5ba
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 3

    initialization-mode: always
    data: classpath:data/categoria.sql,classpath:data/rol.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    suffix: .html
    cache: false